# Generated by Django 4.2.2 on 2024-08-14 18:50

from django.db import migrations, models
import django.db.models.deletion
import eventex.subscriptions.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0004_alter_subscription_cpf_alter_subscription_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, validators=[eventex.subscriptions.validators.validate_cpf], verbose_name='CPF')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('observation', models.CharField(blank=True, max_length=2500, verbose_name='Observação')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscription', verbose_name='Aluno')),
            ],
        ),
    ]
