# Generated by Django 4.2.2 on 2024-09-05 18:21

from django.db import migrations, models
import eventex.subscriptions.validators


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'Participante', 'verbose_name_plural': 'Participantes'},
        ),
        migrations.AlterField(
            model_name='registration',
            name='cpf',
            field=models.CharField(max_length=14, validators=[eventex.subscriptions.validators.validate_cpf], verbose_name='CPF'),
        ),
    ]
