# Generated by Django 4.2.2 on 2024-09-26 17:59

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_registration_options_alter_registration_cpf'),
    ]

    operations = [
        UnaccentExtension(),
    ]
