# Generated by Django 4.2.2 on 2024-10-30 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_talk_options'),
        ('registration', '0004_registration_name_speaker_registration_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations_as_courses', to='core.course', verbose_name='Nome do Curso'),
        ),
    ]
