# Generated by Django 4.2.2 on 2024-12-10 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_talk_options'),
        ('registration', '0004_registration_name_speaker_registration_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='name_speaker',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='talk',
        ),
        migrations.CreateModel(
            name='ItensTalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_speaker', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Palestrante')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Horário de Início')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.registration')),
                ('talk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations_as_talks', to='core.talk', verbose_name='Nome da Palestra')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItensCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_speaker', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Palestrante')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Horário de Início')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations_as_courses', to='core.course', verbose_name='Nome do Curso')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.registration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
