# Generated by Django 4.2.2 on 2025-02-18 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_remove_registration_name_speaker_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itenscourse',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='itenstalk',
            options={'verbose_name': 'Palestra', 'verbose_name_plural': 'Palestras'},
        ),
    ]
