# Generated by Django 4.2.2 on 2024-09-05 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_courseold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talk',
            options={'ordering': ['start'], 'verbose_name': 'palestra', 'verbose_name_plural': 'palestras'},
        ),
    ]
